// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrN8sjMnI9n-PjvGRVFdMgbYtOzDqrJww',
    appId: '1:731991688341:web:c64d8cd62d81b15a3f479c',
    messagingSenderId: '731991688341',
    projectId: 'sjaeger-cmsc4303-flutter',
    authDomain: 'sjaeger-cmsc4303-flutter.firebaseapp.com',
    storageBucket: 'sjaeger-cmsc4303-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT84iJbD4r_Jpc88OcGiqkkmSHMNlQjKQ',
    appId: '1:731991688341:android:52ba5c6205745acc3f479c',
    messagingSenderId: '731991688341',
    projectId: 'sjaeger-cmsc4303-flutter',
    storageBucket: 'sjaeger-cmsc4303-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3v4CEM0q9LPY317tuv07o-M3rWc_U8V0',
    appId: '1:731991688341:ios:a11f2204b3b27cc63f479c',
    messagingSenderId: '731991688341',
    projectId: 'sjaeger-cmsc4303-flutter',
    storageBucket: 'sjaeger-cmsc4303-flutter.appspot.com',
    iosBundleId: 'edu.uco.sjaeger.cmsc4303.lesson6',
  );

}